import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {createBoardingHandler} from './boarding.mjs';
import {BUCKET,seal,unseal,validateDetails,fileType} from './boarding-crypto.mjs';
import {issueToken} from './lead.mjs';
const env={RESEND_API_KEY:'test-resend',MAIL_FROM:'Test <test@example.com>',SUPABASE_URL:'https://db.example',SUPABASE_SERVICE_ROLE_KEY:'test-service',BOARDING_ENCRYPTION_KEY:randomBytes(32).toString('base64')};
const origin='https://guidedpayments.com',id='12345678-1234-4234-8234-123456789abc';
const details={dba:'TEST ONLY',legalName:'Test Business',businessPhone:'2395550100',businessEmail:'test@example.com',ein:'00-0000000',ownerName:'Test Owner',ownerPhone:'2395550100',ssn:'000-00-0000',paymentNeeds:'Both',acceptance:'Blended',consent:true};
function harness(){const objects=new Map(),emails=[];let clock=Date.now(),failEmail=false,failSave=false;const send=async(url,init={})=>{
 if(url==='https://api.resend.com/emails'){if(failEmail)return new Response('',{status:500});emails.push(JSON.parse(init.body));return Response.json({id:'test-email-'+emails.length});}
 const base=env.SUPABASE_URL+'/storage/v1/object/';
 if(url===base+'list/'+BUCKET){const options=JSON.parse(init.body);return Response.json([...objects.keys()].filter(k=>k.startsWith(options.prefix+'/')).map(k=>({name:k.split('/').pop()})).slice(options.offset,options.offset+options.limit));}
 assert.ok(url.startsWith(base+BUCKET+'/'));const path=url.slice((base+BUCKET+'/').length);
 if(init.method==='POST'){if(failSave)return new Response('',{status:500});if(objects.has(path))return Response.json({statusCode:'409'},{status:400});objects.set(path,Buffer.from(init.body));return Response.json({Key:path});}
 return objects.has(path)?new Response(objects.get(path)):Response.json({statusCode:'404'},{status:400});
 };const handle=createBoardingHandler({send,now:()=>clock});
 const call=(path,data={},cookie='',foreign=false)=>handle(new Request(origin+'/api/boarding/'+path,{method:'POST',headers:{origin:foreign?'https://evil.example':origin,'Content-Type':'application/json',cookie},body:JSON.stringify(data)}),env);
 return {objects,emails,call,setEmailFailure:v=>failEmail=v,setStorageFailure:v=>failSave=v,advance:n=>clock+=n,token:async()=> (await issueToken(env,clock-2000).json()).token,start:async()=>call('start',{id,details,token:(await issueToken(env,clock-2000).json()).token})};
}
test('boarding encrypts and authenticates bytes and binds each object to its path',()=>{const plain=Buffer.from('sensitive test data'),encrypted=seal(plain,env,'one');assert.equal(encrypted.includes(plain),false);assert.deepEqual(unseal(encrypted,env,'one'),plain);assert.throws(()=>unseal(encrypted,env,'two'));encrypted[15]^=1;assert.throws(()=>unseal(encrypted,env,'one'));});
test('boarding validates identity fields and document signatures',()=>{assert.equal(validateDetails(details).ssn,'000000000');assert.throws(()=>validateDetails({...details,ein:'not-a-number'}));assert.throws(()=>validateDetails({...details,consent:false}));assert.throws(()=>fileType(Buffer.from('<script>alert(1)</script>')));assert.equal(fileType(Buffer.from('%PDF-1.7 test')).extension,'pdf');});
test('public submission stores encrypted details/documents and sends no tax identifiers or attachments',async()=>{const h=harness(),start=await h.start();assert.equal(start.status,200);const {capability}=await start.json();const file=Buffer.from('%PDF-1.7 TEST DOCUMENT ONLY');assert.equal((await h.call('upload',{capability,kind:'bank',file:file.toString('base64')})).status,200);assert.equal((await h.call('submit',{capability,documents:['bank']})).status,200);assert.equal((await h.call('submit',{capability,documents:['bank']})).status,200);assert.equal(h.emails.length,1);assert.deepEqual(h.emails[0].to,['sean@guidedpayments.com']);assert.ok(!JSON.stringify(h.emails[0]).includes('000000000'));assert.equal(h.emails[0].attachments,undefined);for(const bytes of h.objects.values()){assert.equal(bytes.includes(Buffer.from('TEST ONLY')),false);assert.equal(bytes.includes(file),false);}assert.equal((await h.call('upload',{capability,kind:'license',file:file.toString('base64')})).status,409);});
test('unauthenticated readers, forged capabilities, cross-origin requests, changed retries and missing uploads are rejected',async()=>{const h=harness();for(const route of ['list','detail','reveal','document'])assert.equal((await h.call(route,{id,kind:'bank'})).status,401);assert.equal((await h.call('upload',{capability:'fake'})).status,401);assert.equal((await h.call('start',{},'',true)).status,403);const {capability}=await (await h.start()).json();assert.equal((await h.call('submit',{capability,documents:['license']})).status,400);assert.equal((await h.call('start',{id,details:{...details,ownerName:'Changed'},token:await h.token()})).status,409);});
test('storage and email failures cannot report success; retained submissions retry safely',async()=>{const h=harness();h.setStorageFailure(true);assert.equal((await h.start()).status,503);assert.equal(h.emails.length,0);h.setStorageFailure(false);const {capability}=await (await h.start()).json();h.setEmailFailure(true);assert.equal((await h.call('submit',{capability,documents:[]})).status,502);assert.ok(h.objects.has('submissions/'+id));h.setEmailFailure(false);assert.equal((await h.call('submit',{capability,documents:[]})).status,200);});
test('review login is single-use; cookies are secure; reads are masked and audited; logout revokes session',async()=>{const h=harness();const {capability}=await (await h.start()).json();await h.call('upload',{capability,kind:'bank',file:Buffer.from('%PDF-1.7 TEST').toString('base64')});await h.call('submit',{capability,documents:['bank']});assert.equal((await h.call('login',{token:await h.token()})).status,200);const token=h.emails.at(-1).text.match(/sign-in=([a-f0-9]+)/)[1];const signed=await h.call('session',{token});assert.equal(signed.status,200);const header=signed.headers.get('set-cookie');assert.match(header,/Secure; HttpOnly; SameSite=Strict/);const cookie=header.split(';')[0];assert.equal((await h.call('session',{token})).status,401);assert.equal((await h.call('list',{},cookie)).status,200);const record=await (await h.call('detail',{id},cookie)).json();assert.equal(record.details.ssn,'•••-••-0000');assert.equal((await (await h.call('reveal',{id},cookie)).json()).ssn,'000000000');const download=await h.call('document',{id,kind:'bank'},cookie);assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/^attachment/);assert.ok([...h.objects.keys()].filter(k=>k.startsWith('audit/')).length>=4);await h.call('logout',{},cookie);assert.equal((await h.call('list',{},cookie)).status,401);});
test('expired sign-in links and sessions are rejected and login requests have persistent limits',async()=>{const h=harness();await h.call('login',{token:await h.token()});let token=h.emails.at(-1).text.match(/sign-in=([a-f0-9]+)/)[1];h.advance(16*60000);assert.equal((await h.call('session',{token})).status,401);await h.call('login',{token:await h.token()});token=h.emails.at(-1).text.match(/sign-in=([a-f0-9]+)/)[1];const r=await h.call('session',{token});h.advance(31*60000);assert.equal((await h.call('list',{},r.headers.get('set-cookie').split(';')[0])).status,401);for(let i=0;i<3;i++)assert.equal((await h.call('login',{token:await h.token()})).status,200);assert.equal((await h.call('login',{token:await h.token()})).status,429);});
