import {receiptHero,inquiryForm} from './brand.mjs';
export const equipmentOptions = ['Help me choose','Clover','Clover Flex','Clover Mini','Clover Station','Clover Station Duo','Quantic','Tonic','Square POS','Dejavoo P1','Dejavoo P Series','Dejavoo QD Line','Valor VL550','Valor Next-Gen Series','Priority Pay Center','Keep my current POS'];
export const equipmentPrices = {'Clover Flex':'$49.99/mo','Clover Mini':'$59.99/mo','Clover Station':'$99.99/mo','Clover Station Duo':'$119.99/mo'};
export const businessTypes = ['Restaurant / café','Retail store','Professional services','Automotive','Health / wellness','Other'];
export const volumeOptions = ['Under $10,000','$10,000–$30,000','$30,000–$75,000','$75,000–$150,000','$150,000+','Not sure yet'];
export const equipmentPicker = `<details class="equipment-picker" id="equipment-picker"><summary><span class="picker-symbol" aria-hidden="true">▦</span><span><small>YOUR PAYMENT SETUP</small><strong id="picker-selected">Help me choose</strong><small id="picker-price"></small></span><span class="picker-chevron" aria-hidden="true">⌄</span></summary><div class="picker-panel"><p>Choose your equipment</p>${equipmentOptions.map(name=>`<button type="button" class="picker-option" data-equipment="${name}" data-price="${equipmentPrices[name]||''}"><span><strong>${name}</strong><small>${equipmentPrices[name]||(name==='Help me choose'?'Let’s find your fit':'Ask about compatibility')}</small></span><span class="picker-check" aria-hidden="true">✓</span></button>`).join('')}<p class="picker-footnote">Choose an option to include it in your inquiry.</p></div></details>`;
const options = values => values.map(value=>`<option>${value}</option>`).join('');
export const equipment = `<section class="wrap section" id="equipment"><div class="equipment-heading"><div><p class="eyebrow">THE RIGHT TOOLS. THE RIGHT FIT.</p><h2>Meet your next<br>point of sale.</h2></div><p>At the counter, on the floor, or on the go. Let’s find the setup that fits how you work.</p></div><div class="equipment-grid">${[
 ['Clover Flex','flex','On the move','A handheld option to bring checkout to your customer.','Table service · Mobile businesses'],
 ['Clover Mini','mini','Small footprint','A compact countertop option when space is at a premium.','Retail · Quick service'],
 ['Clover Station','station','Your business hub','A countertop system for your everyday sales and operations.','Restaurants · Retail'],
 ['Clover Station Duo','duo','Both sides of the counter','A setup with a screen for you and one for your customer.','Counter service · Retail']
].map(([name,shape,kicker,description,fit])=>`<article class="equipment-card"><div class="product-photo"><img src="/clover-${shape}.png" alt="${name} payment system" loading="lazy" decoding="async"></div><p class="eyebrow">${kicker}</p><h3>${name}</h3><p>${description}</p><p class="fit">${fit}</p><p class="equipment-price">${equipmentPrices[name]}</p><a class="equipment-link" href="#inquiry" data-equipment="${name}">Explore this setup <span aria-hidden="true">↗</span></a></article>`).join('')}</div><p class="pos-positioning">We also offer Quantic and Tonic, and can review compatibility with your existing POS. Let’s find the right fit for your business.</p><p class="micro">Supplied monthly equipment pricing is subject to review. Availability, features, software, and final pricing depend on your selected package and quote.</p><a class="text-link" href="#inquiry" data-equipment="Help me choose">Not sure? Help me choose →</a></section>`;
const comparison = `<section class="soft section" id="compare"><div class="wrap"><div class="section-heading"><p class="eyebrow">SEE THE DIFFERENCE</p><h2>How zero-fee<br>processing works.</h2><p>With dual pricing, customers see a cash price and a card price before they pay. The difference helps cover card acceptance costs. Here’s how that compares with traditional processing.</p></div><div class="comparison-table"><table><thead><tr><th scope="col">What changes?</th><th scope="col">Traditional processing</th><th scope="col">Guided program options</th></tr></thead><tbody><tr><th scope="row">Card processing costs</th><td>Generally paid by your business</td><td>Eligible costs offset through your pricing program</td></tr><tr><th scope="row">Customer pricing</th><td>Usually one posted price</td><td>Clear cash and card pricing for dual pricing</td></tr><tr><th scope="row">Equipment & software</th><td>Depends on your provider</td><td>Matched to your needs; terms provided in your quote</td></tr><tr><th scope="row">Your next step</th><td>Review your current statement</td><td>Compare your total cost with a personal estimate</td></tr></tbody></table></div><div class="comparison-bottom"><p>We’ll walk through the full picture with you.<br>No guesswork about what’s included.</p><a class="button" href="/zero-fee-inquiry">Get my savings estimate <span aria-hidden="true">↗</span></a></div></div></section>`;
export function reviseHome(home) {
 const rest=home.slice(home.indexOf('<div class="trust-strip">'));
 return receiptHero+rest.replace('<section class="wrap section process">',comparison+equipment+'<section class="wrap section process">').replace(/<section class="wrap final-cta">[\s\S]*?<\/section>/,inquiryForm(equipmentOptions,volumeOptions)).replaceAll('href="/zero-fee-inquiry"','href="#inquiry"');
}
export const inquiryPage = inquiryForm(equipmentOptions,volumeOptions);
