const branches=[
 {id:'pos',label:'POS systems',sub:'Clover · Quantic · Tonic · Square',color:'#92d9ad',url:'/pos-center',x:220,y:90},
 {id:'terminals',label:'Terminal families',sub:'Dejavoo · Valor · Clover Flex',color:'#b7a2ff',url:'/terminal-center',x:220,y:240},
 {id:'pricing',label:'Pricing & analysis',sub:'Dual pricing · Statement review',color:'#ff98b6',url:'/statement-analyzer',x:220,y:390},
 {id:'payments',label:'Payment tools',sub:'Invoices · Recurring · QuickBooks',color:'#7ce4df',url:'/payments-center',x:980,y:90},
 {id:'business',label:'Business services',sub:'Payroll · Funding · Financing',color:'#ffcb7c',url:'/#inquiry',x:980,y:240},
 {id:'support',label:'Setup & support',sub:'Installation · Training · Local help',color:'#83baff',url:'/#inquiry',x:980,y:390}
];
export const homeNetwork=`<section class="home-network" id="payments-universe" aria-labelledby="network-heading"><div class="wrap"><div class="network-heading"><div><p class="eyebrow">YOUR BUSINESS. CONNECTED.</p><h2 id="network-heading">One payments person.<br><em>A world of solutions.</em></h2></div><a class="network-full" href="/payments-map">Explore the full map <span aria-hidden="true">↗</span></a></div><div class="network-stage"><svg id="home-network" viewBox="0 0 1200 480" role="group" aria-label="Explore Guided Payments services"><defs><radialGradient id="network-glow"><stop stop-color="#ffbd56" stop-opacity=".16"/><stop offset="1" stop-color="#ffbd56" stop-opacity="0"/></radialGradient></defs><circle class="network-halo" cx="600" cy="240" r="205" fill="url(#network-glow)"/><g aria-hidden="true">${branches.map(n=>`<path class="network-edge" data-edge="${n.id}" d="M600 240 Q${n.x<600?400:800} 240 ${n.x} ${n.y}" stroke="${n.color}"/>`).join('')}</g><a class="network-core" href="/payments-map" transform="translate(600,240)" aria-label="Guided Payments: explore the full map"><circle r="79"/><text y="-6" text-anchor="middle">Guided</text><text y="23" text-anchor="middle">Payments</text><text class="network-core-sub" y="48" text-anchor="middle">POWERED BY PRIORITY</text></a>${branches.map(n=>`<a class="network-node" data-node="${n.id}" data-x="${n.x}" data-y="${n.y}" href="${n.url}" transform="translate(${n.x},${n.y})" aria-label="${n.label}: ${n.sub}"><rect x="-167" y="-40" width="334" height="80" rx="16"/><circle cx="-143" cy="-7" r="5" fill="${n.color}"/><text class="network-label" x="-128" y="-1">${n.label}</text><text class="network-sub" x="-143" y="23">${n.sub}</text><text class="network-arrow" x="139" y="-2" text-anchor="end" fill="${n.color}">↗</text></a>`).join('')}</svg><div class="network-bottom"><p>Drag to rearrange. Click a node to explore.</p><div><button id="network-motion" type="button" aria-pressed="false">Pause motion</button><button id="network-reset" type="button">Reset</button></div></div></div></div></section>`;
