import test from 'node:test';
import assert from 'node:assert/strict';
import {createLeadHandler,issueToken} from './lead.mjs';
import {createServer} from './server.mjs';
import {once} from 'node:events';
const env={RESEND_API_KEY:'test-secret',MAIL_FROM:'Guided Payments <noreply@merchantlens.ai>',SUPABASE_URL:'https://storage.example',SUPABASE_SERVICE_ROLE_KEY:'server-only'};
const clock=Date.now();
const token=(await (await issueToken(env,clock-2000)).json()).token;
const lead={name:'Test Owner',email:'owner@example.com',phone:'2395550100',organization:'Test Business',cardVolume:'$10,000–$30,000',equipment:'Clover Mini',message:'Test inquiry',submissionId:'12345678-1234-4234-8234-123456789abc',token};
const request=(data,origin='https://guidedpayments.com')=>new Request('https://guidedpayments.com/api/lead',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(data)});
function mock({failStore=false,failEmail=false}={}){const rows=new Map(),calls=[];return {rows,calls,send:async(url,init={})=>{calls.push({url,init});if(url.startsWith('https://storage.example')){if(failStore)return new Response('',{status:500});if(init.method==='POST'){const row=JSON.parse(init.body);if(!rows.has(row.id))rows.set(row.id,row);return new Response(null,{status:201});}if(init.method==='PATCH'){Object.assign(rows.get(lead.submissionId),JSON.parse(init.body));return new Response(null,{status:204});}return Response.json(url.includes('?id=')?[...rows.values()]:[]);}assert.equal(url,'https://api.resend.com/emails');return failEmail?new Response('',{status:500}):Response.json({id:'verified-test-receipt'});}};}
test('saves first, sends only to Sean, and prevents repeat storage/email',async()=>{const m=mock(),handle=createLeadHandler({...m,now:()=>clock});assert.equal((await handle(request(lead),env)).status,200);assert.equal(m.rows.size,1);assert.ok(m.calls.findIndex(c=>c.init.method==='POST'&&c.url.includes('storage'))<m.calls.findIndex(c=>c.url.includes('resend')));const email=m.calls.find(c=>c.url.includes('resend'));assert.deepEqual(JSON.parse(email.init.body).to,['sean@guidedpayments.com']);assert.equal(JSON.parse(email.init.body).reply_to,lead.email);assert.equal((await handle(request(lead),env)).status,200);assert.equal(m.calls.filter(c=>c.url.includes('resend')).length,1);assert.equal((await handle(request({...lead,organization:'Changed'}),env)).status,409);});
test('validates required fields, choices, token, honeypot, and foreign origin',async()=>{for(const data of [{...lead,email:'invalid'},{...lead,phone:'1'},{...lead,equipment:'Free terminal'},{...lead,cardVolume:''},{...lead,website:'spam'},{...lead,token:'forged'}]){const m=mock();assert.equal((await createLeadHandler({...m,now:()=>clock})(request(data),env)).status,400);assert.equal(m.calls.length,0);}assert.equal((await createLeadHandler()(request(lead,'https://foreign.example'),env)).status,403);});
test('storage failure stops email; email failure retains saved lead and reports failure',async()=>{const a=mock({failStore:true});assert.equal((await createLeadHandler({...a,now:()=>clock})(request(lead),env)).status,503);assert.ok(!a.calls.some(c=>c.url.includes('resend')));const b=mock({failEmail:true});const response=await createLeadHandler({...b,now:()=>clock})(request(lead),env);assert.equal(response.status,502);assert.equal(b.rows.size,1);assert.match((await response.json()).error,/saved/);});
test('missing configuration cannot report success; signed token expires',async()=>{assert.equal(issueToken({}).status,503);assert.equal((await createLeadHandler()(request(lead),{})).status,503);const stale=createLeadHandler({now:()=>clock+3*3600000});assert.equal((await stale(request(lead),env)).status,400);});
test('new equipment choices are accepted',async()=>{for(const equipment of ['Quantic','Tonic','Keep my current POS','Help me choose']){const m=mock();assert.equal((await createLeadHandler({...m,now:()=>clock})(request({...lead,equipment}),env)).status,200);}});
test('all routes render, metadata and prices survive, testimonial removed, source files hidden',async()=>{const server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;try{for(const p of ['/home-page','/zero-fee-inquiry','/zero-fee-thank-you','/privacy','/gp-brand.png','/guided.css','/favicon.svg'])assert.equal((await fetch(base+p)).status,200);const html=await(await fetch(base+'/home-page')).text();assert.match(html,/Guided Payments/);assert.match(html,/sean@guidedpayments.com/);assert.match(html,/id="monthly-cost"/);assert.match(html,/id="lead-form"/);assert.doesNotMatch(html,/class="equipment-card"/);const pos=await(await fetch(base+'/pos-center')).text();assert.match(pos,/\$119.99\/mo/);assert.match(pos,/class="equipment-card"/);assert.match(html,new RegExp('© '+new Date().getFullYear()));assert.doesNotMatch(html,/Kristin|Jonathan|sean@ppssfl.com|YEAR_PLACEHOLDER/);assert.equal((await fetch(base+'/.env')).status,404);assert.equal((await fetch(base+'/lead.mjs')).status,404);}finally{await new Promise(resolve=>server.close(resolve));}});
