import {test} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createServer} from './server.mjs';
const lead={name:'Test Owner',email:'owner@example.com',phone:'2395550100',organization:'Test Business',businessType:'Retail store',zip:'33901',cardVolume:'$10,000–$30,000',equipment:'Clover Mini',message:'Test inquiry',submissionId:'12345678-1234-4234-8234-123456789abc'};
async function run(config,fn){const server=createServer(config);server.listen(0,'127.0.0.1');await once(server,'listening');try{await fn(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
const post=(base,data,headers={})=>fetch(`${base}/api/lead`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(data)});
test('all three funnel routes and assets load; source files stay private',()=>run({},async base=>{for(const path of ['/home-page','/zero-fee-inquiry','/zero-fee-thank-you','/privacy','/style.css','/app.js'])assert.equal((await fetch(base+path)).status,200);assert.equal((await fetch(base+'/.env')).status,404);assert.equal((await fetch(base+'/server.mjs')).status,404);}));
test('invalid fields and foreign origins cannot send',()=>run({},async base=>{assert.equal((await post(base,{...lead,email:'bad'})).status,400);assert.equal((await post(base,{...lead,phone:'1'})).status,400);assert.equal((await post(base,lead,{Origin:'https://foreign.example'})).status,403);assert.equal((await post(base,{...lead,website:'spam'})).status,400);}));
test('missing configuration cannot produce success',()=>run({env:{}},async base=>assert.equal((await post(base,lead)).status,503)));
test('business choices and ZIP are validated before delivery',()=>run({},async base=>{assert.equal((await post(base,{...lead,equipment:'Unknown device'})).status,400);assert.equal((await post(base,{...lead,zip:'bad'})).status,400);assert.equal((await post(base,{...lead,cardVolume:''})).status,400);}));
test('provider failures cannot produce success',()=>run({env:{RESEND_API_KEY:'test',MAIL_FROM:'test@example.com'},send:async()=>new Response('{}',{status:500})},async base=>assert.equal((await post(base,lead)).status,502)));
test('successful handoff routes only to Sean and uses lead reply-to',()=>run({env:{RESEND_API_KEY:'test',MAIL_FROM:'test@example.com'},send:async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');const body=JSON.parse(options.body);assert.deepEqual(body.to,['sean@ppssfl.com']);assert.equal(body.reply_to,lead.email);assert.ok(options.headers['Idempotency-Key'].includes(lead.submissionId));return Response.json({id:'test-receipt'});}},async base=>{const response=await post(base,lead);assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true});}));
