const terminalOptions = [
  {name:'Dejavoo Series',type:'P Series & QD Line',image:'/terminal-p1.webp',alt:'Dejavoo P1, a countertop option in the P Series',copy:'Explore Dejavoo’s P Series and QD Line for countertop, wireless, mobile, and customer-facing payment setups.',families:[{name:'P Series',interest:'Dejavoo P Series',copy:'Android countertop, wireless, and PIN pad options for everyday checkout.',models:'P1 · P3 · P5 · P8 · P12 · P17 · P18',source:'https://dejavoo.io/products/p-terminals-family/'},{name:'QD Line',interest:'Dejavoo QD Line',copy:'Android terminals for mobile payments, retail counters, and customer-facing checkout.',models:'QD1 · QD2 · QD3 · QD4 · QD5',source:'https://dejavoo.io/products/qd-terminals-family/'}]},
  {name:'Valor Series',interest:'Valor Next-Gen Series',type:'Next-Gen POS',image:'/terminal-vl550.webp',alt:'Valor VL550, one model in the Next-Gen POS series',copy:'Explore Valor’s Next-Gen POS lineup for a payment setup built around your counter, floor, or event. We’ll review the right model, connectivity, tips, and receipt workflow with you.',points:['VL550','VP550','VP550E','VP800'],imageNote:'VL550 shown. Features and connectivity vary by model.',source:'https://valorpaytech.com/what-we-do/hardware-products/next-gen-pos/'},
  {name:'Clover Flex',type:'On the move',image:'/clover-flex.png',alt:'Clover Flex handheld payment device',copy:'Explore handheld checkout with Clover when you want payments and business tools together.',points:['Handheld Clover option','Checkout at the counter or with the customer','Explore the full Clover lineup in our POS Center'],source:'/pos-center'}
];

export const terminalCenter = `<section class="solution-center terminal-center"><div class="wrap"><div class="center-heading"><p class="eyebrow">TERMINAL CENTER</p><h1>Take payments.<br><em>Where your business happens.</em></h1><p>At the counter, across the floor, or on the move. Find equipment that fits your day—with Sean there to help you choose, set up, and get comfortable using it.</p></div><div class="terminal-grid">${terminalOptions.map((t,i)=>`<article class="terminal-card${t.families?' terminal-card-dejavoo':''}"><div class="terminal-card-heading"><span class="center-number">0${i+1}</span><p class="eyebrow">${t.type}</p><h2>${t.name}</h2></div><div class="terminal-photo"><img src="${t.image}" alt="${t.alt}" loading="lazy" decoding="async"></div><div class="terminal-card-body"><p>${t.copy}</p>${t.families?`<div class="terminal-families">${t.families.map(f=>`<section><h3>${f.name}</h3><p>${f.copy}</p><p class="terminal-models">${f.models}</p><a class="button" href="#inquiry" data-equipment="${f.interest}">Explore ${f.name}</a><a class="center-source" href="${f.source}" target="_blank" rel="noopener">View ${f.name} models</a></section>`).join('')}</div><p class="terminal-image-note">P1 shown. We’ll match the model, connectivity, and software to your business.</p>`:''}${!t.families?`<ul>${(t.points||[]).map(p=>`<li>${p}</li>`).join('')}</ul><a class="button" href="#inquiry" data-equipment="${t.interest||t.name}">Explore ${t.name}</a><a class="center-source" href="${t.source}"${t.source.startsWith('https:')?' target="_blank" rel="noopener"':''}>${t.source.startsWith('https:')?'Manufacturer details':'Visit the POS Center'}</a>${t.imageNote?`<p class="terminal-image-note">${t.imageNote}</p>`:''}`:''}</div></article>`).join('')}</div><div class="center-callout"><div><h2>Start with how you work.</h2><p>We’ll review connectivity, printed or digital receipts, tips, and any connection to your current POS. Equipment, software, service costs, and program compatibility are confirmed in your quote.</p></div><a href="#inquiry" class="button" data-equipment="Help me choose">Help me choose</a></div></div></section>`;

const paymentFeatures = [
 ['Smart invoicing','Send professional invoices with deposits or installments, reminders, late fees, and early-payment discounts.'],
 ['Text-to-pay & payment requests','Send a payment request by text or email so customers can pay without a phone call.'],
 ['Payment links & QR codes','Share a payment link online or give customers a QR code with a direct path to payment.'],
 ['Recurring billing','Set up authorized payments for memberships, retainers, subscriptions, and payment plans.'],
 ['Virtual terminal','Accept card-not-present payments for phone orders or remote customers.'],
 ['Customer portal','Give customers a branded place to view invoices, pay balances, and save preferred payment methods.']
];

export const paymentsCenter = `<section class="solution-center payments-center"><div class="wrap"><div class="payments-intro"><div class="center-heading"><p class="eyebrow">PAYMENTS CENTER · PRIORITY PAY CENTER</p><h1>From invoice<br><em>to paid.</em></h1><p>Make it easier to collect deposits, send invoices, and keep recurring payments on schedule. Priority Pay Center brings your receivables together, with personal guidance from Guided Payments.</p><div class="center-actions"><a class="button" href="#inquiry" data-equipment="Priority Pay Center">Request a demo</a><a class="center-source" href="https://priority.paycenter.app/" target="_blank" rel="noopener">Explore Priority Pay Center</a></div></div><aside class="payment-workflow" aria-label="Example invoice payment workflow"><p class="eyebrow">ONE JOB. A CLEAR PATH TO PAYMENT.</p><ol><li><span>01</span><div><h2>Send the invoice</h2><p>Request a deposit, the full balance, or scheduled installments.</p></div></li><li><span>02</span><div><h2>Your customer pays</h2><p>Share a link by text or email with the payment options you’ve enabled.</p></div></li><li><span>03</span><div><h2>Keep your books in sync</h2><p>Connect QuickBooks Online to sync invoices, payments, and customer records.</p></div></li></ol></aside></div><div class="payment-features">${paymentFeatures.map(([name,copy],i)=>`<article><span class="center-number">0${i+1}</span><h2>${name}</h2><p>${copy}</p></article>`).join('')}</div><div class="payment-connections"><article><p class="eyebrow">QUICKBOOKS ONLINE</p><h2>Keep your accounting.<br>Upgrade your payments.</h2><p>Two-way sync keeps invoices, payments, and customer records updated in both systems. We’ll walk through the right workflow for your business.</p></article><article><p class="eyebrow">PAYMENT OPTIONS</p><h2>Give customers a choice.</h2><p>Explore card and ACH payments, with dual pricing that offers a lower price for cash or ACH. We’ll review your processing options, full pricing, and setup together.</p></article></div><div class="center-callout"><div><h2>Let’s see it with your business in mind.</h2><p>Contractors, professional services, memberships, or another workflow—tell Sean how you collect payments today.</p></div><a class="button" href="#inquiry" data-equipment="Priority Pay Center">Request a demo</a></div></div></section>`;

export const homeCenters = `<section class="wrap section home-center-links" aria-label="More payment solutions"><a href="/terminal-center"><p class="eyebrow">TERMINAL CENTER</p><h2>At the counter.<br>On the move.</h2><p>Explore countertop and handheld payment equipment.</p><span>Explore terminals</span></a><a href="/payments-center"><p class="eyebrow">PAYMENTS CENTER</p><h2>Invoice. Collect.<br>Keep moving.</h2><p>Explore Priority Pay Center for invoices, payment links, and recurring billing.</p><span>Explore payment tools</span></a></section>`;
