import {terminalCatalog} from './terminal-catalog.mjs';
const terminalGroups = ['P Series','QD Line','Valor Next-Gen','Clover'];
export const terminalCenter = `<section class="solution-center terminal-center terminal-catalog"><div class="wrap"><div class="center-heading"><p class="eyebrow">TERMINAL CENTER</p><h1>Find your payment terminal.</h1><p>Explore the lineup. Select “More info” to tell Sean which terminal interests you.</p></div>${terminalGroups.map(group=>`<section class="terminal-catalog-group" aria-labelledby="group-${group.toLowerCase().replaceAll(' ','-')}"><h2 id="group-${group.toLowerCase().replaceAll(' ','-')}">${group==='P Series'||group==='QD Line'?'Dejavoo ':''}${group}</h2><div class="terminal-mini-grid">${terminalCatalog.filter(t=>t.group===group).map(t=>`<article class="terminal-mini"><a class="terminal-mini-photo terminal-photo-trigger" href="${t.largeImage}" data-terminal-photo="${t.name}" data-thumbnail="${t.image}" aria-label="Enlarge photo of ${t.name}"><img src="${t.image}" alt="${t.name} payment terminal" width="300" height="300" loading="lazy" decoding="async"><span class="terminal-photo-hint">Enlarge photo</span></a><div class="terminal-mini-body"><h3>${t.name}</h3><p>${t.description}</p><a class="button" href="#inquiry" data-equipment="${t.name}" aria-label="More info about ${t.name}">More info</a></div></article>`).join('')}</div></section>`).join('')}<p class="terminal-catalog-note">We’ll confirm model availability, connectivity, compatible software, and full pricing for your business.</p></div></section><dialog id="terminal-photo-dialog" class="terminal-photo-dialog" aria-labelledby="terminal-photo-title"><div class="terminal-photo-toolbar"><h2 id="terminal-photo-title">Terminal photo</h2><button type="button" class="terminal-photo-close" autofocus>Close</button></div><div class="terminal-photo-stage"><img id="terminal-photo-large" alt=""></div><p id="terminal-photo-status" role="status"></p><a class="button" id="terminal-photo-info" href="#inquiry" data-equipment="Help me choose">More info</a></dialog>`;

const paymentFeatures = [
 ['Smart invoicing','Send professional invoices with deposits or installments, reminders, late fees, and early-payment discounts.'],
 ['Text-to-pay & payment requests','Send a payment request by text or email so customers can pay without a phone call.'],
 ['Payment links & QR codes','Share a payment link online or give customers a QR code with a direct path to payment.'],
 ['Recurring billing','Set up authorized payments for memberships, retainers, subscriptions, and payment plans.'],
 ['Virtual terminal','Accept card-not-present payments for phone orders or remote customers.'],
 ['Customer portal','Give customers a branded place to view invoices, pay balances, and save preferred payment methods.']
];

export const paymentsCenter = `<section class="solution-center payments-center"><div class="wrap"><div class="payments-intro"><div class="center-heading"><p class="eyebrow">PAYMENTS CENTER · PRIORITY PAY CENTER</p><h1>From invoice<br><em>to paid.</em></h1><p>Make it easier to collect deposits, send invoices, and keep recurring payments on schedule. Priority Pay Center brings your receivables together, with personal guidance from Guided Payments.</p><div class="center-actions"><a class="button" href="#inquiry" data-equipment="Priority Pay Center">Request a demo</a><a class="center-source" href="https://priority.paycenter.app/" target="_blank" rel="noopener">Explore Priority Pay Center</a></div></div><aside class="payment-workflow" aria-label="Example invoice payment workflow"><p class="eyebrow">ONE JOB. A CLEAR PATH TO PAYMENT.</p><ol><li><span>01</span><div><h2>Send the invoice</h2><p>Request a deposit, the full balance, or scheduled installments.</p></div></li><li><span>02</span><div><h2>Your customer pays</h2><p>Share a link by text or email with the payment options you’ve enabled.</p></div></li><li><span>03</span><div><h2>Keep your books in sync</h2><p>Connect QuickBooks Online to sync invoices, payments, and customer records.</p></div></li></ol></aside></div><div class="payment-features">${paymentFeatures.map(([name,copy],i)=>`<article><span class="center-number">0${i+1}</span><h2>${name}</h2><p>${copy}</p></article>`).join('')}</div><div class="payment-connections"><article><p class="eyebrow">QUICKBOOKS ONLINE</p><h2>Keep your accounting.<br>Upgrade your payments.</h2><p>Two-way sync keeps invoices, payments, and customer records updated in both systems. We’ll walk through the right workflow for your business.</p></article><article><p class="eyebrow">PAYMENT OPTIONS</p><h2>Give customers a choice.</h2><p>Explore card and ACH payments, with dual pricing that offers a lower price for cash or ACH. We’ll review your processing options, full pricing, and setup together.</p></article></div><div class="center-callout"><div><h2>Let’s see it with your business in mind.</h2><p>Contractors, professional services, memberships, or another workflow—tell Sean how you collect payments today.</p></div><a class="button" href="#inquiry" data-equipment="Priority Pay Center">Request a demo</a></div></div></section>`;

export const homeCenters = `<section class="wrap section home-center-links" aria-label="More payment solutions"><a href="/terminal-center"><p class="eyebrow">TERMINAL CENTER</p><h2>At the counter.<br>On the move.</h2><p>Explore countertop and handheld payment equipment.</p><span>Explore terminals</span></a><a href="/payments-center"><p class="eyebrow">PAYMENTS CENTER</p><h2>Invoice. Collect.<br>Keep moving.</h2><p>Explore Priority Pay Center for invoices, payment links, and recurring billing.</p><span>Explore payment tools</span></a></section>`;
